// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG7vx5LOU5bLZ4gs70-A_47ZNzrEAFgMo',
    appId: '1:624093324864:web:c9bd38c9b484ca0915e1a5',
    messagingSenderId: '624093324864',
    projectId: 'sufel-event-app-2026',
    authDomain: 'sufel-event-app-2026.firebaseapp.com',
    storageBucket: 'sufel-event-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7S6TeazRZ6gDNfZHipgq9e6fWjQt9gYc',
    appId: '1:624093324864:android:8f964eb7a4c7eca615e1a5',
    messagingSenderId: '624093324864',
    projectId: 'sufel-event-app-2026',
    storageBucket: 'sufel-event-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmpqFy37iIbF0e07-tzI2ZQIiQL1sp730',
    appId: '1:624093324864:ios:342fda50cd77d24d15e1a5',
    messagingSenderId: '624093324864',
    projectId: 'sufel-event-app-2026',
    storageBucket: 'sufel-event-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.eventManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmpqFy37iIbF0e07-tzI2ZQIiQL1sp730',
    appId: '1:624093324864:ios:342fda50cd77d24d15e1a5',
    messagingSenderId: '624093324864',
    projectId: 'sufel-event-app-2026',
    storageBucket: 'sufel-event-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.eventManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG7vx5LOU5bLZ4gs70-A_47ZNzrEAFgMo',
    appId: '1:624093324864:web:923d9df7d20f4add15e1a5',
    messagingSenderId: '624093324864',
    projectId: 'sufel-event-app-2026',
    authDomain: 'sufel-event-app-2026.firebaseapp.com',
    storageBucket: 'sufel-event-app-2026.firebasestorage.app',
  );
}
